app = "lui-relay"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "9000"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
