name: Publish Packages

on:
  release:
    types: [published, released]

jobs:
  publish-pypi:
    if: "!github.event.release.prerelease"
    name: Publish to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lui-python
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*

  publish-npm:
    if: "!github.event.release.prerelease"
    name: Publish to npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lui-node
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
